### ISSUE TITLE
[conan-center] White list for Conan Center Index

### ISSUE THREAD

**Issue by uilianries** [conan-io/hooks#119]
Hi!

It's annoying when a package has a specific limitation which is not included in Conan Center hook, but is really required. For those cases, we have been included the package name in the hook.

So far, so good, it has been worked. However, for each package, we need to open a new PR for hooks, which blocks the CCI PR.

Other projects, like pylint, pyflakes, pycov, ... use a hidden files on root level to customize the original behavior. Using this approach, hardcoded names are not longer needed in the code, and the same code can be executed locally.

Example:

```ini
# conan-center-index/.conan-hooks
[whitelist]
kb30 = cccl, poco
kb11 = boost
```

The hook Conan-Center can detect that file, valid those rules, and skip only the specifics packages for the KB rule.

#### Pros
- Don't need to open a new PR for hook, only for whitelist
- Don't need to use hardcoded package names in hook file

#### Cons
- Any user can manage the whitelist on same CCI PR.

**Comment by Croydon** [comment]
I'm thinking it would be too easy to make too many exceptions or maybe merge exceptions which aren't reviewed carefully. 

So having a small barrier for adding exceptions sounds good to me as this might prevent them from being used too extensively.

**Comment by uilianries** [comment]
I see, but at least we have dual review in CCI.

**Comment by markgalpin** [comment]
I agree we need careful review and I'd prefer not to have someone be able to "slip in" a whitelist mod and have us miss it somehow -- which might be a reason to put it in another repository.  That said, I also want to be able to scale where needed.  In particular it would probably be good to have a consolidated list of exceptions to the rules documented in a single location, that is relatively clear and simple to add-remove packages from, without screwing with the code for individual hooks.

Question for @uilianries in your mechansim, what would we do if an exception is required for one version of a recipe, but later versions (possibly due to a code change, or other types of changes) do not require the exception?

**Comment by uilianries** [comment]
> Question for @uilianries in your mechansim, what would we do if an exception is required for one version of a recipe, but later versions (possibly due to a code change, or other types of changes) do not require the exception?

This is a good question. We don't have such feature for the current hooks, but we could associate the version, e.g. kh30 = `boost/1.70.0`

**Comment by uilianries** [comment]
I see what you are talking about. I remember two situations in the past, in a company we had whitelist file, but it was protected on server side, and in another company we had the whitelist on same project repo.

The first was safer, because only the devops team could approve a new package in the whitelist, and they didn't need to review package recipes. But, the process was slow, well it was the cost for safety.

The second one was faster, but also I saw some users trying to push their by force, putting in the whitelist.

So, considering your comments and remembering about my past experiences, I think keeping the whitelist here will be safer. Thanks for giving your opinions.
