### ISSUE TITLE
validate_recursive exception in conan-center.py

### ISSUE THREAD

**Issue by harsszegi** [conan-io/hooks#296]
Hello,
I need to extend the conandata.yml with a string array within "sources", like:

components: ["foo","bar"]

However if I do that, conan-center.py crashes in KB-H030/validate_recursive, as:

"if isinstance(e, str) and e not in allowed_sources and not isinstance(data[e], str):"

crashes as "e" is not an integer. Please check whether it is possible to change this line:

"if isinstance(e, str) and e not in allowed_sources and isinstance(e, int) and not isinstance(data[e], str):"

Thanks,

**Comment by Croydon** [comment]
The `conandata.yml` is not meant to be arbitrarily modified. If there is some need for extensions, we have to discuss the use case first

**Comment by harsszegi** [comment]
Hi,
the use case is for Boost for example (not your recipe, but our custom one) where we wish to control the components to be built.
Furthermore there are “strange” 3rd party libraries which are not released properly, in those cases we usually add a custom field as well which maps the “strange” versioning (not following semver) to a “sane” one.
Funny thing though is that adding a new field (not an array) would not cause any issue, at least no KB is activated at all in that case.

**Comment by uilianries** [comment]
The Conan Center hook is officially designed for Conan Center only, that's why we can't customize it, we only allow fields which all recipes should use there. For your specific case, you can ignore that or disable conan-center hook. 

You could temporally disable conan-center hook by envvar:

    export CONAN_HOOKS=attribute_checker

It will enable attribute_checker hook only.

Or, 

    conan config rm hooks.conan-center 


I will suggest it as local configuration for global.conf feature too, so you can add a single file in your repository.

**Comment by harsszegi** [comment]
Aok, thanks for the info
