### ISSUE TITLE
Credentials of bintray plugin env vars

### ISSUE THREAD

**Issue by lasote** [conan-io/hooks#36]
About these variables:
```
CONAN_LOGIN_USERNAME: Bintray login username
CONAN_PASSWORD: Bintray API KEY
```
I know that these variables are used in CPT, but even these I would like to rename them.
I think would make more sense to name them as "BINTRAY_XXX" even check if there are some "standard" variables maybe in the jfrog cli?

**Comment by uilianries** [comment]
Actually they are from Conan:

https://docs.conan.io/en/latest/reference/env_vars.html#conan-login-username-conan-login-username-remote-name
https://docs.conan.io/en/latest/reference/env_vars.html#conan-password-conan-password-remote-name

I'm curious, why not reuse it? Since the user is able to execute the `conan upload` and use these env vars, I thought that the best option would be to reuse them, otherwise we would need to replicate both values.

**Comment by lasote** [comment]
Are you using Conan to update the bintray properties? If the answer is no, I think the name shouldn't be about Conan but about Bintray

**Comment by uilianries** [comment]
Indirectly yes, I need Conan to run this hook, since it uses Conan API.

**Comment by lasote** [comment]
But not for updating properties.
For me that is coupling two different things.
