### ISSUE TITLE
[suggestion] Move the check for mixed settings into hooks

### ISSUE THREAD

**Issue by Minimonium** [conan-io/hooks#77]
https://github.com/conan-io/conan/issues/4602

There is no need to scare consumers of the recipe by these warnings.

**Comment by danimtb** [comment]
I don't think we can move those warnings out of the Conan client right now without improving the management of those settings for cross-building. Also, as hooks are a customization of the Conan client, I don't really see anyone activating a hook with just a warning on purpose...

**Comment by Minimonium** [comment]
@danimtb The problem is the purpose of this warning. Currently, it's pretty hard to implement build tools. 
Technically it's only important for advanced recipe authors, But it also visible for consumers, which is unwanted behavior. 
The alternative way could be to make a Conan default hook as the attribute checker.

**Comment by danimtb** [comment]
The attribute checker was built-in in the client in order to not change the output, however, recent updates were only included in the "external" hook. We are currently not going to force the installation of any hook as it is a point of customization for users.

I agree that the warning message is ugly for consumers, but we cannot move the warning out of Conan. Would it be possible to warn only to package creators?

**Comment by Minimonium** [comment]
It can be done, maybe exactly before the pre_export stage, I'd write some tests for it later.
My main intention was to clean this bit out of the main repository, fewer corner cases the better! 
But then I guess I don't understand the difference between intentions of hooks and this warning.

**Comment by Minimonium** [comment]
Closed by https://github.com/conan-io/conan/pull/6021
