### ISSUE TITLE
[conan center] check there is no version if all is used

### ISSUE THREAD

**Issue by SSE4** [conan-io/hooks#83]
if recipe is in `all` directory, it shouldn't specify any `version`

**Comment by lasote** [comment]
The `all` folder is just a convention and any other pattern could be used (e.g: 1.1.X and 1.2.X) so it would be incomplete. Anyway, it will fail during creation because of the processed reference from the yml file mismatching the version in the recipe. I don't think we need a hook for this. Please confirm.

**Comment by SSE4** [comment]
for me it never failed on CI, and I always was asked to remove the version field in PRs. it would be nice if hook reminds about it by itself.

**Comment by lasote** [comment]
> for me it never failed on CI 

Because the version matches the config.yml entry? Examples?

**Comment by SSE4** [comment]
yeah, I think so - example was yasm
in this case, if CI is not failed, having a version is OK, right?

**Comment by lasote** [comment]
Yes. In that case, the wrong thing might be the "all" folder? LoL

**Comment by SSE4** [comment]
yes, let's keep the version in this case, as it's harmless
